#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin install

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Functions --------------------------------

composer_install ()
{
	echo-green "Installing dependencies..."
	fin composer install
}

#-------------------------- Execution --------------------------------

# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
fin project reset -f

# Site initialization
echo -e "${green_bg} Step 2 ${NC}${green} Initializing site...${NC}"
cp .env.example .env
echo "APP_ENV='local'" > .env
#fin p up
time -p composer_install
echo -e "${green_bg} Step 3 ${NC}${green} Install project from existing config.${NC}"
time -p fin drupal build
fin drush uli

echo -e "${green_bg} DONE! ${NC}${green} Completed all initialization steps.${NC}"

#-------------------------- END: Execution --------------------------------
